### ISSUE TITLE
UNSAT certification is invalid.

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/splr#96]
## Description
- version: Splr-0.6.3 to 0.7.0

## Solution
- resolved at Splr-0.7.1 RC

## Reason
- the order of clause generation and deletion operations was shuffled by `garbage_collect`!

**Comment by shnarazk** [comment]
```text
$ splr -c cnfs/unif-k3-r4.25-v360-c1530-S1028159446-096.cnf
unif-k3-r4.25-v360-c1530-S1028159446-096.cnf       360,1530 |time:   261.62
 #conflict:    1494762, #decision:      1909826, #propagate:       77459509
  Assignment|#rem:      351, #ass:        1, #elm:        8, prg%:   2.5000
      Clause|Remv:   100721, LBD2:      723, Binc:       16, Perm:     1519
     Restart|#BLK:        0, #RST:    11832, trgr:        1, peak:       64
         LBD|avrg:  10.2625, trnd:   1.1722, depG:   2.6848, /dpc:     1.17
    Conflict|tASG:   0.9978, cLvl:    10.00, bLvl:     8.85, /ppc:    53.91
        misc|elim:       10, #sub:        4, core:      168, /cpr:   388.27
clause vivifying(assert:0, purge:951 shorten:0, check:1000/2851)...thread 'main' panicked at 'assertion failed: 
!really_dead', src/solver/vivify.rs:135:25
$ fg                      
```

**Comment by shnarazk** [comment]
## Symptom 2 

The conflicting clause isn't the asssumed clause.

```text
aes.cnf                                      501284,2928183 |time:   597.35
 #conflict:    1030104, #decision:      2726679, #propagate:      221482579
  Assignment|#rem:    14229, #ass:   238555, #elm:   248500, prg%:  97.1615
      Clause|Remv:   177248, LBD2:     6897, Binc:     8402, Perm:   742806
     Restart|#BLK:     1086, #RST:     1079, trgr:        1, peak:       32
         LBD|avrg:  23.6551, trnd:   1.1018, depG:   3.0953, /dpc:     1.86
    Conflict|tASG:   0.8777, cLvl:   336.32, bLvl:   334.40, /ppc:   382.25
        misc|elim:       22, #sub:   101893, core:        4, /cpr:  2053.35
clause vivifying(assert:0, purge:0 shorten:37, check:12000/92908)...thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3941172C`,
 right: `5306322C`', src/solver/vivify.rs:141:29
```

**Comment by shnarazk** [comment]
## Symptom 3

Learnt is an empty clause.

```text
aes.cnf                                      501284,2928183 |time:   829.82
 #conflict:    1436931, #decision:      3473065, #propagate:      269532636
  Assignment|#rem:    11556, #ass:   241178, #elm:   248550, prg%:  97.6947
      Clause|Remv:   211735, LBD2:     6566, Binc:     7808, Perm:   725250
     Restart|#BLK:     1527, #RST:     1285, trgr:        8, peak:       32
         LBD|avrg:  21.4192, trnd:   1.1336, depG:   3.1192, /dpc:     1.60
    Conflict|tASG:   1.2874, cLvl:   324.56, bLvl:   322.50, /ppc:   290.30
        misc|elim:       21, #sub:   103260, core:        4, /cpr:  2114.12
clause vivifying(assert:0, purge:0 shorten:0, check:0/91498)...thread 'main' panicked at 'assertion failed: !cdb[cc].is_empty()', src/solver/vivify.rs:149:25
```

## reason

`propagate_sandox` fail to skip dead clauses.

**Comment by shnarazk** [comment]
## Symptom 4

The decision literal which is the direct reason for a conflict doesn't locate in the first position of the learnt clause.

```text
$ splr -t 10000 aes.cnf 
aes.cnf                                      501284,2928183 |time:   249.79
 #conflict:     537896, #decision:      1589290, #propagate:      101946939
  Assignment|#rem:    16025, #ass:   236958, #elm:   248301, prg%:  96.8032
      Clause|Remv:    98267, LBD2:     5145, Binc:     8739, Perm:   753734
     Restart|#BLK:      704, #RST:      815, trgr:        1, peak:       32
         LBD|avrg:  22.5748, trnd:   2.2546, depG:   3.3273, /dpc:     4.11
    Conflict|tASG:   1.0150, cLvl:   405.21, bLvl:   402.93, /ppc:   332.79
        misc|elim:       16, #sub:   101749, core:        4, /cpr:  1227.72
clause vivifying(assert:0, purge:0 shorten:0, check:0/39128)...
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-364542L`,
 right: `-367111L`', src/solver/vivify.rs:337:9
```

**Comment by shnarazk** [comment]
## Symptom 5

Splr sometimes determines 'aes.cnf' is UNSAT even if :
```
c   state::Vivification                             26
c   state::VivifiedClause                            0
c   state::VivifiedVar                               0
```

So who is the wire-puller?

**Comment by shnarazk** [comment]
### Symptom 6

fail to propagate!?

```
[     65061] vivify:    4, pick:   28685, assert:       7, shorten:    1808
[     65061] #cycle:    4, core:        18, level:        1, /cpr:   159.59
[    130463] (vivify) root level propagation remains unpropagated literals
[    130463] (vivify) root level propagation remains unpropagated literals
[    130463] vivify:    5, pick:   30246, assert:       2, shorten:    2233
[    273933] (vivify) root level propagation remains unpropagated literals
[    273933] vivify:    6, pick:   47050, assert:       1, shorten:    3138
[    396194] #cycle:    4, core:        10, level:        8, /cpr:   164.44
[    491726] vivify:    7, pick:  100000, assert:       0, shorten:   14276
[    687081] vivify:    8, pick:   58027, assert:       0, shorten:    5421
[    787402] #cycle:    4, core:         4, level:        1, /cpr:   153.10
[    887768] vivify:    9, pick:   82889, assert:       0, shorten:   10221
aes.cnf                                      501284,2928183 |time:   751.97
 #conflict:     887768, #decision:      4681733, #propagate:      127034366
  Assignment|#rem:     8205, #ass:   245647, #elm:   247432, prg%:  98.3632
      Clause|Remv:   110596, LBD2:     2973, Binc:     6030, Perm:   753068
     Restart|#BLK:     1451, #RST:      850, trgr:        1, peak:       16
         LBD|avrg:  17.5684, trnd:   1.3974, depG:   3.7612, /dpc:     2.95
    Conflict|tASG:   1.7268, cLvl:   198.11, bLvl:   196.04, /ppc:    94.15
        misc|proc:       17, #sub:    84753, core:        4, /cpr:  1373.44
```

**Comment by shnarazk** [comment]
### Sympton 7

assigned but unpropagated literals in `asg.trail` are canceled.

```tail
aes.cnf                                      501284,2928183 |time:    48.73
 #conflict:          0, #decision:       136317, #propagate:         242531
  Assignment|#rem:    31846, #ass:   242531, #elm:   226907, prg%:  93.6471
      Clause|Remv:        0, LBD2:        0, Binc:     2666, Perm:   847595
     Restart|#BLK:        0, #RST:        0, trgr:        1, peak:        1
         LBD|avrg:   0.0000, trnd:      NaN, depG:   0.0000, /dpc:     0.00
    Conflict|tASG:      NaN, cLvl:     0.00, bLvl:     0.00, /ppc:     0.00
        misc|proc:        1, #sub:    29316, core:   271288, /cpr:     0.00
thread 'main' panicked at 'unpropagated assigned var 489626Var { index: 489626, participated: 0, reward: 0.037581926534160245, timestamp: 0, flags: (empty) } (3457 in trail[0, 3089, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3347, 3348, 3349, 3350, 3351, 3352, 3354, 3355, 3356, 3357, 3359, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3386, 3387, 3388, 3389, 3390, 3392, 3393, 3395, 3396, 3397, 3398, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482, 3483, 3484, 3485]) found, staying at 318', src/assign/propagate.rs:208:13

**Comment by shnarazk** [comment]
```text
aes.cnf                                      501284,2928183 |time: 28012.68
 #conflict:   18488885, #decision:     63683800, #propagate:     4390205413
  Assignment|#rem:     8075, #ass:   245399, #elm:   247810, prg%:  98.3891
      Clause|Remv:   441999, LBD2:    32010, Binc:     9563, Perm:  1017364
     Restart|#BLK:    10437, #RST:    12544, trgr:        1, peak:       64
         LBD|avrg:   3.0112, trnd:   0.4228, depG:   4.5263, /dpc:     1.25
    Conflict|tASG:   1.0085, cLvl:    12.08, bLvl:    10.81, /ppc:    10.28
        misc|proc:       87, #sub:    78979, core:        1, /cpr:   243.15
      Result|file: ./ans_aes.cnf
 Certificate|file: aes.drat
s UNSATISFIABLE: aes.cnf
```
